### ISSUE TITLE
Web Speech API - detect and synthesize

### ISSUE THREAD

**Issue by macbre** [Wikia/ask-fandom#4]
## TODO list

* [ ] build a simple Flask app
* [ ] expose `/ask` API endpoint that will respond with an answer for the provided question
* [ ] create a simple web page that will allow user to say his question and hear the answer

## Browser API

https://www.google.com/intl/en/chrome/demos/speech.html // https://davidwalsh.name/speech-recognition

https://w3c.github.io/speech-api/#tts-section

**Comment by macbre** [comment]
```js
  speechSynthesis.speak(new SpeechSynthesisUtterance('Hello World'));
```
